### ISSUE TITLE
WriteUp_module2_pregunta6

### ISSUE THREAD

**Issue by ch4m17ux** [c1b3rwall/module2#12]
_**Gracias a Roberto Perez que ha realizado este write-up, solo lo estoy compartiendo con todos vosotros.  Todo el merito y agradecimiento es para El**._

_Documento original: https://mega.nz/file/NEFQiaoI#Jmr3ooBqiaHZJYtJLLoLLSn3hQ0yWkg5SeZHFvTGVuc_

**SOLUCION:**

Se nos da una señal en formato raw y la abrimos en Audacity para ver de que se trata (importar datos en bruto) dejamos los parametros por defecto.

En la ventana de abajo podemos ver la señal (onda+espectro), es evidente (si aun no lo notamos mas adelante si) que la señal inferior es la portadora (data) sin embargo por los momentos no la descartamos. 

Si hacemos un muestreo de los datos y lo exportamos podemos ver en el Inspectrum una alternativa para visualizar (ajustando los parametros) la amplitud, frecuencia y fase de la señal, entendiendo que la señal debemos demodularla para extraer la data descartamos este camino.

**_Conceptos básicos:_**
Para que una señal viaje a través de ondas de radio, primero debe modularse, lo que significa trasponerla a un ancho de banda de frecuencia y formato adecuados para el medio de transmisión. Las técnicas de modulación están estrechamente relacionadas con las telecomunicaciones y la teoría de la información, y es posible jugar con la modulación dentro de los límites de una computadora.

**_Passband_**
Una banda de paso es el rango de frecuencias o longitudes de onda que pueden pasar a través de un filtro. Por ejemplo, un receptor de radio contiene un filtro de paso de banda para seleccionar la frecuencia de la señal de radio deseada entre todas las ondas de radio captadas por su antena. La banda de paso de un receptor es el rango de frecuencias que puede recibir. Una señal con filtro de paso de banda (es decir, una señal con energía solo en una banda de paso) se conoce como señal de paso de banda, en contraste con una señal de banda base.

En telecomunicaciones, óptica y acústica, una banda de paso (una señal filtrada de paso de banda) es la parte del espectro de frecuencia que se transmite (con una pérdida relativa mínima o una ganancia relativa máxima) por algún dispositivo de filtrado. En otras palabras, es una banda de frecuencias que pasa por algún filtro o un conjunto de filtros. La figura adjunta muestra un esquema de una forma de onda que se filtra mediante un filtro de paso de banda que consta de un filtro de paso alto y uno de paso bajo. Los receptores de radio generalmente incluyen un filtro de paso de banda sintonizable con una banda de paso que es lo suficientemente amplia para acomodar el ancho de banda de la señal de radio transmitida por una sola estación.Una señal con filtro de paso de banda (es decir, una señal con energía solo en una banda de paso) se conoce como señal de paso de banda, en contraste con una señal de banda base.

Hay  dos  categorías  principales  de  métodos  de  transmisión de comunicaciones digitales:  banda  base  y  banda  de  paso.  En la transmisión de banda base, se utiliza codificación de línea, lo que da como resultado un tren de pulsos o una señal modulada en amplitud de pulso (PAM).En la transmisión de banda de paso, se emplean métodos de modulación digital de modo que sólo se utilice un rango de frecuencia limitado en algún canal filtrado de banda de paso. La transmisión de banda de paso se utiliza típicamente en comunicaciones inalámbricas y en canales filtrados de paso de banda como las líneas POTS. También permite la multiplexación por división de frecuencia. El flujo de bits digital se convierte primero en una señal de banda base equivalente y luego en una señal de RF. En el lado del receptor se utiliza un demodulador para detectar la señal e invertir el proceso de modulación. Un equipo combinado de modulación y demodulación se denomina módem.

Señal sin restricciones (diagrama superior). Filtro de paso de banda aplicado a la señal Higth pass filter- Low pass filter (diagrama del medio). Señal filtrada (diagrama inferior). A(f) es la función de frecuencia de la señal.
(wikipedia.org/wiki/Passband)

Evidentemente la señal necesita ser tratada para interpretarla, entendiendo estos conceptos regresamos a Audacity justamente como habiamos importado el raw. Si hacemos un acercamiento podemos ver que la señal superior no sufre ninguna alteración en el transcurso de la misma (tiene un patrón definido y constante) a diferencia de la inferior (que podria tener la codificación) separamos el audio (mono) y descartamos la superior.

La  codificación de mensajes se basa en la codificación por desplazamiento de frecuencia, que es una técnica de modulación en la que una señal digital se convierte en analógica  reemplazando  el  encendido  y  apagado  o  el  uno  lógico  y  el  cero con dos frecuencias portadoras diferentes (por eso luego vamos duplicar esta señal para separar cada una en dos frecuencias distintas), en este caso la mayor de las dos frecuencias representa un 1 y la frecuencia más baja se usa para 0.

La modulación AM exige que la señal esté restringida a un ancho de banda, por lo que la señal modulada también "encajará" en una banda de frecuencia predeterminada. Entonces, necesitamos aplicar un filtro de paso (Passband) y definimos el corte a 6408 Hz.

Duplicamos la señal y aplicamos el Passband, Filtro de paso Alto en la señal superior y Filtro de paso bajo (equivalente a un condensador y una resistencia) en la inferior con 6408 Hz y 48db.

En este punto básicamente tenemos dos señales moduladas en amplitud donde la de arriba son los datos que queremos y el de abajo el inverso de eso (con la modulación de amplitud, la envolvente de la onda portadora es la señal de entrada).

Ahora con el indicador de Nyquist simplemente tomamos el valor absoluto del sonido usando este comando (s-abs sound) en cada una de las señales (es equivalente a ejecutar la señal a través de un puente rectificador).

Ya tenemos la señal demodulada, seguidamente aplicamos un filtro paso bajo de nuevo pero a las dos señales para obtener la envolvente (en los mismos parametros) y amplificamos (por separado cada señal, dejamos los valores por defectos). 

Luego invertirmos la señal inferior (efectos>invertir), seleccionando ambas señales las mezclamos.

Finalmente obtenemos la señal filtrada.

Decodificamos

01101101	01101111	01100100	01110101	01101100	01100101	00110010	01111011
01101000	01100101	01110010	01100101	01011111	01101001	01110011	01011111
01110100	01101000	01100101	01011111	01010011	01000100	01010010	01011111
01100110  	01101100        00110100  	01100111  	01111101

**Nota**: El procedimiento expuesto es la demodulación manual, hay otra alternativa para ahorranos todo este proceso con SDR Nyquist effect plugins para Audacity.

Un simple complemento de efectos Nyquist para convertir señales I / Q (en fase y en cuadratura)  a  Amplitud  /  Fase  (señales  de  radio  de  decodificación  AM).  Analizar  y decodificar señales On-Off-Keying (OOK) / Amplitude-Shift-Keying (ASK) grabadas por ej. Software RTL-SDR con Audacity

Roberto Perez

**Comment by djdanielnieto** [comment]
Excelente trabajo

**Comment by Toni-Geminis** [comment]
Muy buena explicación. Muchas gracias.
